Escreva um programa, em Python, para resolver um sistema de n equações lineares e n incógnitas usando o método de iterativo de Gauss-Jacobi. Os dados de entrada devem ser: a) o número de equações n; b) a matriz aumentada [A b]. A saída deve ser  o vetor solução [x] ou uma mensagem informando que o método não convergiu. Explique o critério de parada usado.


In [1]:
import numpy as np

In [2]:
#Método Gauss-Jacobi
n = input("Número de equações: ")
n = int(n)

#Matriz A
A = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        A[i][j] = input("A[%d][%d]: " % (i,j))
        
#Vetor b
b = np.zeros((n,1))
for i in range(n):
    b[i] = input("b[%d]: " % (i))

#Vetor x
x = np.zeros((n,1))

#método de Gauss-Jacobi com critério de parada de diagonal dominante
stopFlag = 0
while True:
    for i in range(n):
        soma = 0
        for j in range(n):
            if j != i:
                soma = soma + A[i][j]*x[j]
                
        x[i] = (b[i] - soma)/A[i][i]
        
    #Critério de parada
    #Diagonal dominante
    soma = 0
    
    for i in range(n):
        for j in range(n):
            if j != i:
                soma = soma + abs(A[i][j])
        if abs(A[i][i]) < soma:
            print("Matriz não é diagonal dominante")
            stopFlag += 1
            break
        soma = 0
    if stopFlag == n:
        print("Método não converge")
        break
        
    erro = 0
    soma = 0
    for i in range(n):
        soma = 0
        for j in range(n):
            soma = soma + A[i][j]*x[j]
        soma = soma - b[i]
        erro = erro + soma
    if abs(erro) < n*(10**(-6)):
        break
    
    

ValueError: invalid literal for int() with base 10: ''

In [ ]:
print("Solução:")
print(x)

Solução:
[[ 8.]
 [10.]]


Uma empresa fabrica três tipos de móveis: cadeiras, mesas e armários. Cada móvel requer uma quantidade de madeira, plástico e alumínio, conforme a tabela abaixo. A empresa tem em estoque 400 unidades de madeira, 600 unidades de plástico e 1500 unidades de alumínio. Por ser final de temporada, a empresa quer usar todo o seu estoque. Para fazer isso, quantas cadeiras, mesas e armários ela precisa fabricar? Use o método de iterativo de  Gauss-Jacobi. 

Cadeira
1 unidade de madeira
1 unidade de plástico
2 unidades de alumínio
Mesa
1 unidade de madeira
1 unidade de plástico
3 unidades de alumínio
Armário
1 unidade de madeira
2 unidades de plástico
5 unidades de alumínio

PRECISÃO 10^(-6)  se convergir.

As equações são:
x+y+z=400
x+y+2z=600
2x+3y+5z=1500

Determinando a matriz A:
[0 -1 -1]
[-1 0 -2]
[-2/5 -3/5 0]


Portanto a matriz A é:
[(1 1 1)
(1 1 2)
(2 3 5)]


O vetor b é:
[400 600 1500]

In [ ]:
import numpy as np

#Método Gauss-Jacobi
n = 3

#Matriz A
A = [[1,1,1],[1,1,2],[2,3,5]]
        
#Vetor b
b = [400,600,1500]

#Vetor x
x = np.zeros((n,1))


#Critério de parada
#Diagonal dominante
stopFlag = 0
soma = 0
for i in range(n):
        for j in range(n):
            if j != i:
                soma = soma + abs(A[i][j])
        if abs(A[i][i]) < soma:
            stopFlag = 1
        soma = 0
        
if stopFlag == 1:
    print("Matriz não é diagonal dominante")
    print("Método não converge")
    
#método de Gauss-Jacobi
while stopFlag == 0:
    print("iteração")
    for i in range(n):
        soma = 0
        for j in range(n):
            if j != i:
                soma = soma + A[i][j]*x[j]
                
        x[i] = (b[i] - soma)/A[i][i]    
    erro = 0
    for i in range(n):
        soma = 0
        j = 0
        for j in range(n):
            soma = soma + A[i][j]*x[j]
        soma = soma - b[i]
        erro = erro + soma
        print("Iteração: ", i, j)
        print("Soma: ", soma)
        print("Erro: ", erro)
        if abs(erro) < n*(10**(-6)):
            break
    erro = 0
    
if(stopFlag == 0):
    print("Solução:")
    print(x)

In [1]:
import numpy as np

def lagrange_interpolation(x, y, x_interp):
    """
    Calcula o valor interpolado usando o polinômio de Lagrange.
    
    Parâmetros:
    - x: Lista dos valores x dos pontos conhecidos.
    - y: Lista dos valores y dos pontos conhecidos.
    - x_interp: Valor de x para o qual queremos interpolar.
    
    Retorna:
    - O valor interpolado para x_interp.
    """
    n = len(x)
    result = 0.0
    
    for i in range(n):
        term = y[i]
        for j in range(n):
            if j != i:
                term *= (x_interp - x[j]) / (x[i] - x[j])
        result += term
    
    return result

# Função original
def f(x):
    return 2 * (x**2) * np.exp(x) + 1

# Pontos conhecidos
x_points = [0, 0.5]
y_points = [f(x) for x in x_points]

# Pontos para interpolação
x_interp_0 = 0
x_interp_1 = 0.5

# Interpolação usando o polinômio de Lagrange
result_0 = lagrange_interpolation(x_points, y_points, x_interp_0)
result_1 = lagrange_interpolation(x_points, y_points, x_interp_1)

# Resultados
print(f"Para x = {x_interp_0}, f(x) ≈ {result_0}")
print(f"Para x = {x_interp_1}, f(x) ≈ {result_1}")


Para x = 0, f(x) ≈ 1.0
Para x = 0.5, f(x) ≈ 1.824360635350064
